package by.epam.autoshow.model;

public enum BodyType {
    CABRIOLET, COUPE, LIMOUSINE, MINIBUS, MINIVAN, THREE_DOOR_SUV, FIVE_DOOR_SUV,
    PICKUP, SEDAN, STATION_WAGGON, THREE_DOOR_HATCHBACK, FIVE_DOOR_HATCHBACK,
    PASSENGER_VAN, OTHER
}